
sector_stocks = {
     "^CNXAUTO": ["M&M.NS","MOTHERSON.NS","MARUTI.NS","BAJAJ-AUTO.NS","EICHERMOT.NS",
                  "UNOMINDA.NS","TMPV.NS","ASHOKLEY.NS","BHARATFORG.NS","HEROMOTOCO.NS",
                  "TVSMOTOR.NS", "TIINDIA.NS","SONACOMS.NS","BOSCHLTD.NS","EXIDEIND.NS"
          ],
    "^CNXIT": ["TECHM.NS","INFY.NS","TCS.NS","WIPRO.NS","COFORGE.NS","HCLTECH.NS","OFSS.NS","PERSISTENT.NS","MPHASIS.NS","LTM.NS"],
    "^NSEBANK": ["HDFCBANK.NS","ICICIBANK.NS","YESBANK.NS","KOTAKBANK.NS","AXISBANK.NS","RBLBANK.NS","BANDHANBNK.NS","IDFCFIRSTB.NS","FEDERALBNK.NS","INDUSINDBK.NS"],
    "^CNXMEDIA": ["SAREGAMA.NS","NAZARA.NS","ZEEL.NS","PVRINOX.NS","SUNTV.NS","NETWORK18.NS","TIPSMUSIC.NS","HATHWAY.NS","PFOCUS.NS","DBCORP.NS"],
    "^CNXCONSUM": ["AMBER.NS","DIXON.NS","KALYANKJIL.NS","TITAN.NS","PGEL.NS","VOLTAS.NS","CROMPTON.NS","BLUESTARCO.NS","LGEINDIA.NS","HAVELLS.NS","WHIRLPOOL.NS","KAJARIACER.NS","BATAINDIA.NS"],
     "NIFTY_FIN_SERVICE.NS": ["BSE.NS","HDFCBANK.NS","SBIN.NS","ICICIBANK.NS","SHRIRAMFIN.NS","JIOFIN.NS","BAJFINANCE.NS","MUTHOOTFIN.NS","KOTAKBANK.NS",
                         "PFC.NS","RECLTD.NS","AXISBANK.NS","BAJAJFINSV.NS","HDFCLIFE.NS","SBILIFE.NS","CHOLAFIN.NS","LICHSGFIN.NS","MFSL.NS","SBICARD.NS","ICICIGI.NS"],
    "^CNXPHARMA": ["GLAND.NS","LAURUSLABS.NS","SUNPHARMA.NS","DRREDDY.NS","CIPLA.NS","BIOCON.NS","WOCKPHARMA.NS","TORNTPHARM.NS","AUROPHARMA.NS","DIVISLAB.NS",
                "LUPIN.NS","ZYDUSLIFE.NS","GLENMARK.NS","IPCALAB.NS","MANKIND.NS","JBCHEPHARM.NS","ABBOTINDIA.NS","PPLPHARMA.NS","AJANTPHARM.NS","ALKEM.NS"],
    "^CNXREALTY":["LODHA.NS","DLF.NS","ANANTRAJ.NS","PHOENIXLTD.NS","GODREJPROP.NS","PRESTIGE.NS","OBEROIRLTY.NS","ABREL.NS","SOBHA.NS","BRIGADE.NS"],
    "^CNXPSUBANK": ["SBIN.NS","PNB.NS","CANBK.NS","BANKBARODA.NS","BANKINDIA.NS","UNIONBANK.NS","INDIANB.NS","MAHABANK.NS","CENTRALBK.NS","UCOBANK.NS","IOB.NS","PSB.NS"],
     "^CNXFMCG": ["ITC.NS","GODREJCP.NS","NESTLEIND.NS","HINDUNILVR.NS","BRITANNIA.NS","VBL.NS","PATANJALI.NS","TATACONSUM.NS","UNITDSPR.NS","MARICO.NS","DABUR.NS","RADICO.NS","UBL.NS","COLPAL.NS","EMAMILTD.NS"],
     "^CNXMETAL":["TATASTEEL.NS","HINDCOPPER.NS","VEDL.NS","SAIL.NS","ADANIENT.NS","HINDZINC.NS","JSWSTEEL.NS","HINDALCO.NS","NATIONALUM.NS","NMDC.NS","LLOYDSME.NS","JINDALSTEL.NS","WELCORP.NS","APLAPOLLO.NS","JSL.NS"]

}
